/* DO NOT EDIT THIS FILE - it is machine generated */
#include "..\JNI_Includes\jni.h"
/* Header for class FakeAutomationJava */

#ifndef _Included_FakeAutomationJava
#define _Included_FakeAutomationJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FakeAutomationJava
 * Method:    DoSomeStuff
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FakeAutomationJava_DoSomeStuff
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
