/* DO NOT EDIT THIS FILE - it is machine generated */
#include "automationapi_Part.h"
#include "..\AppPartOps\PartOps.h"
#include "..\AppPartOps\Journaling_Part.h"
/* Header for class automationapi_Part */


void JNICALL Java_automationapi_Part_save
(JNIEnv* env, jobject thePart)
{
	jclass jCls = env->GetObjectClass( thePart);
	jfieldID guidId = env->GetFieldID( jCls, "m_guid", "I");
	jint guid = env->GetIntField(thePart, guidId);

	Application::PartFile* part = dynamic_cast<Application::PartFile*>(GuidObjectManager::GetGuidObjectManager().GetObjectFromGUID(guid));
	if (part == nullptr)
	{
		throw std::exception("not able to retrieve Part Object");
	}
	else
	{
		Journaling_Part_Save(part);
	}

}
