/* DO NOT EDIT THIS FILE - it is machine generated */
#include "..\JNI_Includes\jni.h"
/* Header for class automationapi_Session */

#ifndef _Included_automationapi_Session
#define _Included_automationapi_Session
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     automationapi_Session
 * Method:    initSession
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_automationapi_Session_initSession
  (JNIEnv *, jobject);

/*
 * Class:     automationapi_Session
 * Method:    makePart
 * Signature: (Ljava/lang/String;)Lautomationapi/Part;
 */
JNIEXPORT jobject JNICALL Java_automationapi_Session_makePart
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
