/* DO NOT EDIT THIS FILE - it is machine generated */
#include "..\JNI_Includes\jni.h"
/* Header for class automationapi_Part */

#ifndef _Included_automationapi_Part
#define _Included_automationapi_Part
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     automationapi_Part
 * Method:    save
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_automationapi_Part_save
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
